services:
  server:
    build:
      context: .
      target: final
    ports:
      - 5000:8080
    env_file:
      - .env
    environment:
      - S3Settings__Region=${S3Settings__Region}
      - S3Settings__BucketName=${S3Settings__BucketName}
      - S3Settings__AccessKey=${S3Settings__AccessKey}
      - S3Settings__SecretAccessKey=${S3Settings__SecretAccessKey}
