services:
  - type: web
    runtime: docker
    name: s3-api-server
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: S3Settings__Region
        value: ${S3_REGION}
      - key: S3Settings__BucketName
        value: ${S3_BUCKET_NAME}
      - key: S3Settings__AccessKey
        value: ${S3_ACCESS_KEY}
      - key: S3Settings__SecretAccessKey
        value: ${S3_SECRET_ACCESS_KEY}